filetype plugin indent on
syntax on
" enable delete on backspace
set backspace=indent,eol,start
" disable swap files
set noswapfile
" allow to open file without saving current one
set hidden
" set runtime path to be curret folder only
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set path=.,**
